### ISSUE TITLE
Plug-in logic error

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [bonn2/BuddyTP#10]
Some players have reported that BTP does not accept the first TP request, and then quitting the game and joining again will cause the last TP request to be still there and cannot be canceled

**Comment by bonn2** [comment]
Are these players getting multiple buddytp requests? If so they will need to run `/btpaccept <playername>` to specify which. I will look into the log in and out issue though.

**Comment by xiaoyueyoqwq** [comment]
> Are these players getting multiple buddytp requests? If so they will need to run `/btpaccept <playername>` to specify which. I will look into the log in and out issue though.

I'll let them do it, and by the way, I'd like to be able to customize the number of times a player can use teleportation per day in the profile;)

**Comment by bonn2** [comment]
Sorry for the delay, was working on my workflow setup.
This should be fixed in `1.1.0`.
I'll be spinning off the feature request into its own issue for organization as that will take a bit more that a few minutes to add.
